### Authenticate Account
POST http://localhost:8080/api/auth/authenticate
Content-Type: application/json

{
  "email":"admin@kmail.com",
  "password": "blopblopblop"
}
> {%
    client.global.set("auth_token", response.body.token);
%}

<> 2023-04-01T225209.200.json
<> 2023-04-01T223439.200.json
<> 2023-04-01T222839.200.json
<> 2023-03-27T142429.200.json

### Register Account
POST http://localhost:8080/api/auth/register
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Tester 5",
  "email": "test5@hotmail.com",
  "company": "leol",
  "password": "Test Password",
  "accountType": "ADMIN"
}

### Create a form template
POST http://localhost:8080/api/forms
Authorization: Bearer {{auth_token}}

<> 2023-04-01T225242.200.json
<> 2023-04-01T224519.200.json
<> 2023-04-01T223444.200.json
<> 2023-04-01T223443.200.json
<> 2023-03-31T134449.200.json

### Duplicate a form
POST http://localhost:8080/api/forms/4/1/duplicate
Authorization: Bearer {{auth_token}}


### Get All Forms
GET http://localhost:8080/api/forms
Authorization: Bearer {{auth_token}}

### Get Form By Fck
GET http://localhost:8080/api/forms/1/5
Authorization: Bearer {{auth_token}}

### Delete a form
DELETE http://localhost:8080/api/forms/1/1
Authorization: Bearer {{auth_token}}

### Update Form
PUT http://localhost:8080/api/forms/3/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Form Test 4",
  "description": "Form Description 1",
  "is_final": true,
  "fields": [
    {
      "name": "How are you doing",
      "helpText": "",
      "isRequired": true,
      "fieldType": "TEXTBOX",
      "options": {
        "How are you doing": {
          "name": "Question",
          "helpText": "",
          "isRequired": false,
          "fieldType": "RADIOBUTTON",
          "regexId": null,
          "options": {
            "nane": null,
            "anme1": null
          }
        }
      }
    }
  ]
}


### Create a workflow
POST http://localhost:8080/api/workflows
Authorization: Bearer {{auth_token}}

<> 2023-04-01T225251.200.json
<> 2023-04-01T224529.200.json
<> 2023-04-01T223456.200.json
<> 2023-04-01T223455.200.json
<> 2023-04-01T221624.200.json
<> 2023-03-31T193110.200.json

### View a workflow
GET http://localhost:8080/api/workflows/1
Authorization: Bearer {{auth_token}}

### Get Workflow by Account Id
GET http://localhost:8080/api/workflows/getWorkflowsByAccountId/1
Authorization: Bearer {{auth_token}}

### Get Workflow by Account Type
GET http://localhost:8080/api/workflows/getWorkflowsByAccountType/ADMIN
Authorization: Bearer {{auth_token}}

<> 2023-03-28T153320.200.json

### Update Workflow Entirely
PUT http://localhost:8080/api/workflows/updateWorkflow/4
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Updated workflow Name",
  "is_final": true,
  "workflow_form_assignments": [
    {
      "account": {
        "id": "1",
        "name": "account",
        "email": "admin@kmail.com",
        "company": "HELLOOOOOOOOO",
        "accountType": "ADMIN"
      },
      "formId": {"id": 0, "revisionNo": 1}
    },
    {
      "account": {
        "id": "2",
        "name": "vendor",
        "email": "vendor@kmail.com",
        "company": "HELLOOOOOOOOO",
        "accountType": "VENDOR"
      },
      "formId": {"id": 1, "revisionNo": 1}
    }
  ]
}

### Publish a workflow
POST http://localhost:8080/api/workflows/4/publishWorkflow
Authorization: Bearer {{auth_token}}

### Add authorized user to workflow
POST http://localhost:8080/api/workflows/6/authorizedAccount?accountId=2
Authorization: Bearer {{auth_token}}


### Create REGEX
POST http://localhost:8080/api/regex
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name" : "regexone",
  "pattern" : "xxxxxx"
}

### Create a Field with just textbox without regexinto form template created abovee
POST http://localhost:8080/api/fields/create?formId=2&revisionNo=1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Site Evaluation Results",
  "helpText": "laurent",
  "isRequired": true,
  "fieldType": "CHECKBOX",
  "options": {
    "Site Evaluation Results": {
      "name": "",
      "helpText": "",
      "isRequired": false,
      "fieldType": "RADIOBUTTON",
      "options": {
        "Satisfactory": null,
        "Unsatisfactory": null
      }
    }
  }
}


### Create Form Submission
POST http://localhost:8080/api/formsubmission
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "workflow_id": 3,
  "fck": {
    "id": 2,
    "revisionNo": 1
  },
  "submittedBy": 1,
  "fieldResponses": {
    "7" : "answer1",
    "8" : "answer2"
  },
  "reviewer": null
}

### Get Form Submission By Workflow and Form
GET http://localhost:8080/api/formsubmission/getByWorkflowAndForm?workflowId=1&formId=1&revisionNo=1
Authorization: Bearer {{auth_token}}

<> 2023-04-01T224927.200.json
<> 2023-04-01T224925.200.json
<> 2023-04-01T223633.200.json
<> 2023-04-01T223632.200.json
<> 2023-04-01T223546.200.json

### Get Form Submission By Account Id
GET http://localhost:8080/api/formsubmission/getByAccountId?accountId=1
Authorization: Bearer {{auth_token}}

<> 2023-04-01T224947.200.json
<> 2023-04-01T223856.200.json
<> 2023-04-01T223854.200.json
<> 2023-04-01T223840.200.json
<> 2023-04-01T223549.200.json
<> 2023-04-01T223548.200.json
<> 2023-04-01T223317.200.json
<> 2023-04-01T223307.200.json

### Get Form Submission By Status
GET http://localhost:8080/api/formsubmission/getByStatus?status=AWAITING_ADMIN
Authorization: Bearer {{auth_token}}

<> 2023-04-01T225027.200.json
<> 2023-04-01T224952.200.json
<> 2023-04-01T224932.200.json

### Get All Form Submission
GET http://localhost:8080/api/formsubmission
Authorization: Bearer {{auth_token}}

### Get Form Submission By Id
GET http://localhost:8080/api/formsubmission/getById?formSubmissionId=5
Authorization: Bearer {{auth_token}}

### Update Form Submission Status
PUT http://localhost:8080/api/formsubmission/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "status": "REJECTED",
  "reviewer": 0
}

### Get Unsubmitted Form by Account Id
GET http://localhost:8080/api/workflowFormAssignment/getUnsubmitted/1
Authorization: Bearer {{auth_token}}

<> 2023-04-01T225331.200.json
<> 2023-04-01T225223.200.json
<> 2023-04-01T225220.200.json
<> 2023-03-31T171004.200.json
